version: 1
services:
  - type: web
    name: liver-disease-prediction
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
